version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - code-volume:/code/
    depends_on:
      - web
  web:
    build: .
    volumes:
      - code-volume:/code/
    ports:
      - "8000:8000"
    expose:
      - "10000-65000"

volumes:
  code-volume: