version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/code/static
      - ./media:/code/media
    depends_on:
      - web
  web:
    build: .
    ports:
      - "8000:8000"
    expose:
      - "10000-65000"
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"