# Generated by Django 2.0.2 on 2018-02-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180218_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider1', models.IntegerField()),
                ('slider2', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
